# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    pwd
    source /home/simon/karting-v2/venv/bin/activate
    pip3 install -r requirements.txt 
    export FLASK_APP="app.py"
    export DATABASE_URL=$(DATABASE_URL)
    flask db init
    flask db migrate -m "message"
    flask db upgrade
  displayName: 'Run a multi-line script'
