"""upgrade db

Revision ID: 73c9958e659f
Revises: 48bbc50459a3
Create Date: 2021-06-20 14:01:07.418109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c9958e659f'
down_revision = '48bbc50459a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laps', sa.Column('race_type', sa.Text(), nullable=True))
    op.add_column('results', sa.Column('race_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'race_type')
    op.drop_column('laps', 'race_type')
    # ### end Alembic commands ###
